const products = [
  {
    id: 1,
    title: 'Running Shoes',
    description: 'High-performance running shoes with  cushioning and support.',
    price: 79.99,
    category: 'Athletic Footwear',
    imageUrls: ['https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/i/s/c/6-league01-6-running-shoes-for-men-light-grey-original-imagjhn65dwnhvhf.jpeg?q=70', 'https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/h/g/f/6-league01-6-running-shoes-for-men-light-grey-original-imagjhn6tphuyas3.jpeg?q=70','https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/m/h/q/6-league01-6-running-shoes-for-men-light-grey-original-imagjhn68je2bszh.jpeg?q=70','https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/n/z/z/6-league01-6-running-shoes-for-men-light-grey-original-imagjhn6xrend6ar.jpeg?q=70'],
  },
  {
    id: 2,
    title: 'Walking Shoes',
    description: 'Comfortable walking shoes for your everyday activities.',
    price: 59.99,
    category: 'Athletic Footwear',
    imageUrls: ['https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/n/z/e/6-brd-406-brd-466-6-birde-grey-orange-green-original-imag4ysrrhdshzew.jpeg?q=70','https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/6/y/m/6-brd-406-brd-466-6-birde-grey-orange-green-original-imag4ysrzgbenpbh.jpeg?q=70','https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/4/m/z/8-brd-406-brd-476-8-birde-grey-orange-yellow-original-imag5ccytgvuhqk8.jpeg?q=70','https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/f/p/n/-original-imagg4zgaacqnv8e.jpeg?q=70','https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/0/t/d/7-brd-393-394-406-7-birde-grey-original-imag4ysrgyp5aczf.jpeg?q=70'],
  },
  {
    id: 3,
    title: 'Trail Running Shoes',
    description: 'Durable and rugged trail running shoes for outdoor adventures.',
    price: 89.99,
    category: 'Athletic Footwear',
    imageUrls: ['https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/f/e/m/-original-imagg6rcqgg295jj.jpeg?q=70','https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/p/j/c/-original-imaghvb4qbjqckyd.jpeg?q=70','https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/n/q/a/6-11g-677-6-campus-t-blu-blk-original-imagh28gucgpfmby.jpeg?q=70','https://rukminim2.flixcart.com/image/832/832/kfh5ifk0-0/shoe/s/l/n/5g-677-6-campus-t-blu-blk-original-imafvxc9pnfw9rr9.jpeg?q=70'],
  },
  {
    id: 4,
    title: 'Sneakers',
    description: 'Classic and stylish sneakers for a casual look.',
    price: 49.99,
    category: 'Casual Footwear',
    imageUrls: ['https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/w/n/2/6-mrj2013-6-aadi-white-red-black-original-imagk4ugjktxwxsf.jpeg?q=70','https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/a/j/p/6-mrj2013-6-aadi-white-red-black-original-imagk4ug3f9cuwbh.jpeg?q=70','https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/w/z/x/6-mrj2013-6-aadi-white-red-black-original-imagk4ugfhkqkpxt.jpeg?q=70','https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/r/f/v/6-mrj2013-6-aadi-white-red-black-original-imagk4ugseeemy46.jpeg?q=70'],
  },
  {
    id: 5,
    title: 'Basketball Shoes',
    description: 'High-top basketball shoes with excellent ankle support.',
    price: 99.99,
    category: 'Athletic Footwear',
    imageUrls: ['https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/y/c/j/-original-imagq9jyjcsx5pgh.jpeg?q=70','https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/5/z/d/-original-imags8nmtfzwtfqe.jpeg?q=70','https://rukminim2.flixcart.com/image/832/832/l4hcx3k0/shoe/p/h/f/-original-imagfdc6ryhvz54g.jpeg?q=70','https://rukminim2.flixcart.com/image/832/832/l4hcx3k0/shoe/r/c/w/-original-imagfdc68u4emehs.jpeg?q=70'],
  },
  {
    id: 6,
    title: 'Hiking Boots',
    description: 'Sturdy hiking boots for challenging terrains.',
    price: 109.99,
    category: 'Outdoor Footwear',
    imageUrls: ['https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/0/r/h/-original-imagg3a7rvfghmms.jpeg?q=70','https://rukminim2.flixcart.com/image/832/832/kdxfc7k0-0/shoe/1/g/u/h20005-furo-blue-original-imafuqfnzcz2xgdn.jpeg?q=70','https://rukminim2.flixcart.com/image/832/832/kdxfc7k0-0/shoe/3/n/u/h20005-furo-blue-original-imafuqfnbweyfy7a.jpeg?q=70','https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/n/w/l/9-h20005-9-furo-blue-original-imaghb94y2hxnbf2.jpeg?q=70'],
  },
  {
    id: 7,
    title: 'Flip Flops',
    description: 'Casual and comfortable flip flops for beach days.',
    price: 19.99,
    category: 'Casual Footwear',
    imageUrls: ['https://rukminim2.flixcart.com/image/832/832/l1zc6fk0/slipper-flip-flop/u/y/t/6-brd-729-birde-black-original-imagdfeehnmfv6tm.jpeg?q=700','https://rukminim2.flixcart.com/image/832/832/l1zc6fk0/slipper-flip-flop/6/q/p/6-brd-729-birde-black-original-imagdfeedbgbsgnj.jpeg?q=70','https://rukminim2.flixcart.com/image/832/832/l1zc6fk0/slipper-flip-flop/p/1/i/6-brd-729-birde-black-original-imagdfeedaerhcqa.jpeg?q=70','https://rukminim2.flixcart.com/image/832/832/l1zc6fk0/slipper-flip-flop/h/n/w/6-brd-729-birde-black-original-imagdfeedhptymyu.jpeg?q=70'],
  },
  {
    id: 8,
    title: 'Dress Shoes',
    description: 'Elegant dress shoes for formal occasions.',
    price: 69.99,
    category: 'Formal Footwear',
    imageUrls: ['https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/u/t/t/-original-imagugww2mght62z.jpeg?q=70','https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/0/a/0/9-para-boot-black-ariwa-black-original-imaghguczasgezhz.jpeg?q=70','https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/r/c/p/9-para-boot-black-ariwa-black-original-imaghguccxedry6z.jpeg?q=70','https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/t/6/f/9-para-boot-black-ariwa-black-original-imaghgucasjbmzue.jpeg?q=70'],
  },
  {
    id: 9,
    title: 'Skate Shoes',
    description: 'Stylish skateboarding shoes with durable design.',
    price: 54.99,
    category: 'Athletic Footwear',
    imageUrls: ['https://rukminim2.flixcart.com/image/832/832/xif0q/skate/k/a/h/free-size-skating-for-kids-inline-skates-skateboards-for-4-to-18-original-imagk9t8gscfhvfk.jpeg?q=70','https://rukminim2.flixcart.com/image/832/832/xif0q/skate/i/s/f/6-9-kids-or-teen-adjustable-inline-skates-for-outdoor-skates-m-original-imagqr6fbh6zfzpq.jpeg?q=70','https://rukminim2.flixcart.com/image/832/832/xif0q/skate/o/q/z/medium-to-large-hight-premium-quality-inline-blue-color-skating-original-imaghjknbrdxfpqy.jpeg?q=70','https://rukminim2.flixcart.com/image/832/832/xif0q/skate/6/y/i/6-9-high-quality-skating-in-line-size-6-9-uk-blue-1-002-in-line-original-imagkru6sf4gwxwm.jpeg?q=70'],
  },
  {
    id: 10,
    title: 'Winter Boots',
    description: 'Insulated winter boots to keep your feet warm in the cold.',
    price: 79.99,
    category: 'Outdoor Footwear',
    imageUrls: ['https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/m/k/8/7-bbma2184-bacca-bucci-black-original-imaghs9tfx4v2wr6.jpeg?q=70','https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/n/e/g/7-bbma2184-bacca-bucci-black-original-imaghs9tuhdhhbdf.jpeg?q=70','https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/b/x/e/7-bbma2184-bacca-bucci-black-original-imaghs9tw829xwgm.jpeg?q=70','https://rukminim2.flixcart.com/image/832/832/xif0q/shoe/j/5/x/7-bbma2184-bacca-bucci-black-original-imaghs9tqqyba2hh.jpeg?q=70'],
  },
];


export default products;
